Update shell.yml

diff --git a/.github/workflows/shell.yml b/.github/workflows/shell.yml
--- a/.github/workflows/shell.yml
+++ b/.github/workflows/shell.yml
@@ -3,32 +3,32 @@ on:
   workflow_dispatch:
   
 jobs:
-  amd_shell:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
+  # amd_shell:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Env Snoop
-      run: |
-        ls -lha
-        pwd
-        whoami
-        df -h
-        echo "env"
-        env
-        echo "id"
-        id
-        echo "groups"
-        groups
-        echo "mounts"
-        mount | column -t
-        sudo su - 
-        cat /etc/hosts
-        ip a
-        ip r
-        curl ifconfig.me
-        curl -I https://nicehash.com || echo "Blocked or failed"
-        sudo dmesg | grep -i hypervisor
+    # - name: Env Snoop
+    #   run: |
+    #     ls -lha
+    #     pwd
+    #     whoami
+    #     df -h
+    #     echo "env"
+    #     env
+    #     echo "id"
+    #     id
+    #     echo "groups"
+    #     groups
+    #     echo "mounts"
+    #     mount | column -t
+    #     sudo su - 
+    #     cat /etc/hosts
+    #     ip a
+    #     ip r
+    #     curl ifconfig.me
+    #     curl -I https://nicehash.com || echo "Blocked or failed"
+    #     sudo dmesg | grep -i hypervisor
         
     # - name: Setup tmate session
     #   uses: mxschmitt/action-tmate@v3
@@ -44,27 +44,27 @@ jobs:
       
     - name: Env Snoop
       run: |
-        ls -lha
-        pwd
-        whoami
-        df -h
-        echo "env"
-        env
-        echo "id"
-        id
-        echo "groups"
-        groups
-        echo "mounts"
-        mount | column -t
-        #dmesg | grep -i hypervisor
-        sudo su - 
-        cat /etc/hosts
+        # ls -lha
+        # pwd
+        # whoami
+        # df -h
+        # echo "env"
+        # env
+        # echo "id"
+        # id
+        # echo "groups"
+        # groups
+        # echo "mounts"
+        # mount | column -t
+        # #dmesg | grep -i hypervisor
+        # sudo su - 
+        # cat /etc/hosts
         ip a
         ip r
         curl ifconfig.me
         curl -I https://nicehash.com || echo "Blocked or failed"
 
-        ping -c 3 169.59.175.190
-        nc -zv 169.59.175.190 22
-        nmap 169.59.175.190
-        ssh -vvv root@169.59.175.190
+        # ping -c 3 169.59.175.190
+        # nc -zv 169.59.175.190 22
+        # nmap 169.59.175.190
+        # ssh -vvv root@169.59.175.190
